### PR TITLE
Review of code layout section and some minor additions

### PR DESCRIPTION
**Pull request by Simran-B**
Also rename file to all upper-case for better visibility.

### CODE REVIEW

**Comment by Simran-B** [comment]
> The cached frames are given a hash which means footage that is reused or moved around does not need to be recached [...]

I think it's worth to point out that there is one cache, which is used for both decoded footage as well as for pre-rendering sequences (this is my understanding at least). A little bit more detail about the hashing would be nice, but I don't actually know how it works.

**Comment by ThomasWilshaw** [comment]
I agree, that might need @itsmattkc input as I'm not very familiar with that code either.

(tagged the wrong MattKC)

**Comment by Simran-B** [comment]
Hash code:
- [RenderManager::Hash](https://github.com/olive-editor/olive/blob/720acb8f77d2cae39b26d232c3607533f9aa6afc/app/render/rendermanager.cpp#L83-L101)
- [Node::Hash](https://github.com/olive-editor/olive/blob/720acb8f77d2cae39b26d232c3607533f9aa6afc/app/node/node.cpp#L408-L476)

Listing everything it takes into account would be too much for the architecture doc, but something more generalized should do.

**Comment by ThomasWilshaw** [comment]
Are you happy for this to be merged now?

**Pull request merged**
